# Generated by Django 2.2 on 2024-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=50, unique=True)),
                ('lastname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('contactnumber', models.CharField(max_length=10)),
                ('department', models.TextField(max_length=100)),
                ('designation', models.TextField(max_length=200)),
            ],
        ),
    ]
